#!/usr/bin/env python3
"""Render the production guest manifest from infra/versions.json.

The JSON file is the only editable version source.  This renderer deliberately
contains repository and package-shape constants, but every selected product
version comes from that JSON document.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import tempfile
from pathlib import Path
from typing import Any, Dict, Optional, Pattern


SEMVER = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")
SHA256 = re.compile(r"^[0-9a-f]{64}$")


def require_mapping(value: Any, name: str) -> Dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError(f"{name} must be an object")
    return value


def require_text(
    mapping: Dict[str, Any], key: str, *, pattern: Optional[Pattern[str]] = None
) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value or "\n" in value or "\r" in value:
        raise ValueError(f"{key} must be a non-empty single-line string")
    if pattern is not None and pattern.fullmatch(value) is None:
        raise ValueError(f"{key} has an invalid value")
    return value


def render(source_bytes: bytes) -> str:
    try:
        document = json.loads(source_bytes)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ValueError("version source is not valid UTF-8 JSON") from error
    root = require_mapping(document, "version source")
    if root.get("schema") != 1:
        raise ValueError("unsupported version source schema")

    ubuntu = require_mapping(root.get("ubuntu"), "ubuntu")
    kubernetes = require_mapping(root.get("kubernetes"), "kubernetes")
    containerd = require_mapping(root.get("containerd"), "containerd")
    crictl = require_mapping(root.get("crictl"), "crictl")

    ubuntu_version = require_text(ubuntu, "version")
    ubuntu_arch = require_text(ubuntu, "arch")
    kubernetes_version = require_text(kubernetes, "version", pattern=SEMVER)
    containerd_version = require_text(containerd, "version", pattern=SEMVER)
    containerd_package = require_text(containerd, "package")
    crictl_version = require_text(crictl, "version", pattern=SEMVER)

    if ubuntu_version != "24.04" or ubuntu_arch != "aarch64":
        raise ValueError("common provisioning supports only Ubuntu 24.04 aarch64")
    if containerd_package != "containerd.io":
        raise ValueError("common provisioning requires the pinned containerd.io package")

    major, minor, _patch = kubernetes_version.split(".")
    kubernetes_minor = f"v{major}.{minor}"
    values = {
        "MANIFEST_SCHEMA": "1",
        "SOURCE_SHA256": hashlib.sha256(source_bytes).hexdigest(),
        "UBUNTU_VERSION": ubuntu_version,
        "UBUNTU_IMAGE_ARCH": ubuntu_arch,
        "DEBIAN_ARCH": "arm64",
        "KUBERNETES_MINOR": kubernetes_minor,
        "KUBERNETES_VERSION": f"v{kubernetes_version}",
        "KUBERNETES_PACKAGE_VERSION": f"{kubernetes_version}-1.1",
        "KUBERNETES_APT_KEY_URL": f"https://pkgs.k8s.io/core:/stable:/{kubernetes_minor}/deb/Release.key",
        "KUBERNETES_APT_KEY_SHA256": "7627818cf7bae52f9008c93e8b1f961f53dea11d40891778de216fb1b43be54d",
        "KUBERNETES_APT_REPOSITORY": f"https://pkgs.k8s.io/core:/stable:/{kubernetes_minor}/deb/",
        "CONTAINERD_PACKAGE_NAME": containerd_package,
        "CONTAINERD_PACKAGE_VERSION": f"{containerd_version}-1~ubuntu.24.04~noble",
        "CONTAINERD_RUNTIME_VERSION": containerd_version,
        "CRI_TOOLS_VERSION": crictl_version,
        "CRI_TOOLS_PACKAGE_VERSION": f"{crictl_version}-1.1",
        "SANDBOX_IMAGE": "registry.k8s.io/pause:3.10.1",
        "DOCKER_APT_KEY_URL": "https://download.docker.com/linux/ubuntu/gpg",
        "DOCKER_APT_KEY_SHA256": "1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570",
        "DOCKER_APT_REPOSITORY": "https://download.docker.com/linux/ubuntu noble stable",
    }
    for key, value in values.items():
        if "\n" in value or "\r" in value or "\x00" in value:
            raise ValueError(f"unsafe generated value for {key}")
    if SHA256.fullmatch(values["SOURCE_SHA256"]) is None:
        raise ValueError("source digest generation failed")

    lines = [
        "# Generated by infra/provision/common/render_versions.py.",
        "# Edit infra/versions.json and rerun the renderer; do not edit this file.",
    ]
    lines.extend(f"{key}={value}" for key, value in values.items())
    return "\n".join(lines) + "\n"


def atomic_write(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(contents)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass


def main() -> int:
    parser = argparse.ArgumentParser()
    operation = parser.add_mutually_exclusive_group(required=True)
    operation.add_argument("--check", action="store_true")
    operation.add_argument("--write", action="store_true")
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    expected = render(args.source.read_bytes())
    if args.check:
        try:
            observed = args.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"generated manifest is missing: {args.output}", file=os.sys.stderr)
            return 1
        if observed != expected:
            print(
                f"generated manifest is stale: run {Path(__file__).name} --write "
                f"--source {args.source} --output {args.output}",
                file=os.sys.stderr,
            )
            return 1
        return 0

    atomic_write(args.output, expected)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError) as error:
        print(f"ERROR: {error}", file=os.sys.stderr)
        raise SystemExit(2)
