#!/usr/bin/env python3
"""Render U5 guest manifests from the single editable infra/versions.json source."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import tempfile
from pathlib import Path


SHA256 = re.compile(r"[0-9a-f]{64}")
SHA512 = re.compile(r"[0-9a-f]{128}")


def _object(value: object, name: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise ValueError(f"{name} must be an object")
    return value


def _text(value: object, name: str, pattern: re.Pattern[str] | None = None) -> str:
    if not isinstance(value, str) or not value or any(c in value for c in "\r\n\0"):
        raise ValueError(f"{name} must be a non-empty single-line string")
    if pattern is not None and pattern.fullmatch(value) is None:
        raise ValueError(f"{name} is invalid")
    return value


def _field(root: dict[str, object], section: str, key: str, pattern=None) -> str:
    value = _object(root.get(section), section).get(key)
    return _text(value, f"{section}.{key}", pattern)


def _manifest(source: bytes, values: dict[str, str]) -> str:
    digest = hashlib.sha256(source).hexdigest()
    lines = [
        "# Generated by infra/provision/render_u5_manifests.py.",
        "# Edit infra/versions.json and rerun the renderer; do not edit this file.",
        f"SOURCE_SHA256={digest}",
    ]
    lines.extend(f"{key}={value}" for key, value in values.items())
    return "\n".join(lines) + "\n"


def render(source: bytes) -> tuple[str, str]:
    try:
        root = _object(json.loads(source), "version source")
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ValueError("version source is not valid UTF-8 JSON") from error
    if root.get("schema") != 1:
        raise ValueError("unsupported version source schema")

    kubernetes = _object(root.get("kubernetes"), "kubernetes")
    kubernetes_version = _text(kubernetes.get("version"), "kubernetes.version")
    tools = {
        "KUBERNETES_VERSION": kubernetes_version,
        "HELM_VERSION": _field(root, "helm", "version"),
        "HELM_URL": _field(root, "helm", "url"),
        "HELM_SHA256": _field(root, "helm", "sha256", SHA256),
        "HELM_INSTALLED_SHA256": _field(root, "helm", "installed_sha256", SHA256),
        "CILIUM_VERSION": _field(root, "cilium", "version"),
        "CILIUM_CLI_VERSION": _field(root, "cilium", "cli_version"),
        "CILIUM_CLI_URL": _field(root, "cilium", "cli_url"),
        "CILIUM_CLI_SHA256": _field(root, "cilium", "cli_sha256", SHA256),
        "CILIUM_CLI_INSTALLED_SHA256": _field(root, "cilium", "cli_installed_sha256", SHA256),
        "ETCDCTL_VERSION": _field(root, "etcdctl", "version"),
        "ETCDCTL_URL": _field(root, "etcdctl", "url"),
        "ETCDCTL_SHA256": _field(root, "etcdctl", "sha256", SHA256),
        "ETCDCTL_INSTALLED_SHA256": _field(root, "etcdctl", "installed_sha256", SHA256),
        "KUBE_BENCH_VERSION": _field(root, "kube_bench", "version"),
        "KUBE_BENCH_MODE": _field(root, "kube_bench", "mode"),
        "KUBE_BENCH_URL": _field(root, "kube_bench", "url"),
        "KUBE_BENCH_SHA256": _field(root, "kube_bench", "sha256", SHA256),
        "KUBE_BENCH_BINARY_INSTALLED_SHA256": _field(root, "kube_bench", "binary_installed_sha256", SHA256),
        "KUBE_BENCH_CONFIG_INSTALLED_SHA256": _field(root, "kube_bench", "config_installed_sha256", SHA256),
        "GVISOR_VERSION": _field(root, "gvisor", "version"),
        "GVISOR_PLATFORM": _field(root, "gvisor", "platform"),
        "GVISOR_RUNSC_URL": _field(root, "gvisor", "runsc_url"),
        "GVISOR_RUNSC_SHA512": _field(root, "gvisor", "runsc_sha512", SHA512),
        "GVISOR_RUNSC_INSTALLED_SHA256": _field(root, "gvisor", "runsc_installed_sha256", SHA256),
        "GVISOR_SHIM_URL": _field(root, "gvisor", "shim_url"),
        "GVISOR_SHIM_SHA512": _field(root, "gvisor", "shim_sha512", SHA512),
        "GVISOR_SHIM_INSTALLED_SHA256": _field(root, "gvisor", "shim_installed_sha256", SHA256),
        "DOCKER_VERSION": _field(root, "docker", "version"),
        "DOCKER_URL": _field(root, "docker", "url"),
        "DOCKER_SHA256": _field(root, "docker", "sha256", SHA256),
        "DOCKER_INSTALLED_SHA256": _field(root, "docker", "installed_sha256", SHA256),
        "FALCO_VERSION": _field(root, "falco", "version"),
        "FALCO_CHART_VERSION": _field(root, "falco", "chart_version"),
        "FALCO_IMAGE": _field(root, "falco", "image"),
        "FALCO_CHART_URL": _field(root, "falco", "chart_url"),
        "FALCO_CHART_SHA256": _field(root, "falco", "chart_sha256", SHA256),
        "FALCO_CHART_INSTALLED_SHA256": _field(root, "falco", "chart_installed_sha256", SHA256),
        "INGRESS_NGINX_VERSION": _field(root, "ingress_nginx", "version"),
        "INGRESS_NGINX_CHART_VERSION": _field(root, "ingress_nginx", "chart_version"),
        "INGRESS_NGINX_CHART_URL": _field(root, "ingress_nginx", "chart_url"),
        "INGRESS_NGINX_CHART_SHA256": _field(root, "ingress_nginx", "chart_sha256", SHA256),
        "INGRESS_NGINX_CHART_INSTALLED_SHA256": _field(root, "ingress_nginx", "chart_installed_sha256", SHA256),
        "BUSYBOX_IMAGE": _field(root, "workload_images", "busybox"),
        "AGNHOST_IMAGE": _field(root, "workload_images", "agnhost"),
        "NGINX_ALPINE_IMAGE": _field(root, "workload_images", "nginx_alpine"),
    }
    candidate = {
        "KUBECTL_VERSION": kubernetes_version,
        "KUBECTL_URL": _text(kubernetes.get("kubectl_url"), "kubernetes.kubectl_url"),
        "KUBECTL_SHA256": _text(kubernetes.get("kubectl_sha256"), "kubernetes.kubectl_sha256", SHA256),
        "TRIVY_VERSION": _field(root, "trivy", "version"),
        "TRIVY_URL": _field(root, "trivy", "url"),
        "TRIVY_SHA256": _field(root, "trivy", "sha256", SHA256),
        "TRIVY_DB_IMAGE": _field(root, "trivy", "db_image"),
        "YQ_VERSION": _field(root, "yq", "version"),
        "YQ_URL": _field(root, "yq", "url"),
        "YQ_SHA256": _field(root, "yq", "sha256", SHA256),
    }
    return _manifest(source, tools), _manifest(source, candidate)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass


def main() -> int:
    parser = argparse.ArgumentParser()
    operation = parser.add_mutually_exclusive_group(required=True)
    operation.add_argument("--check", action="store_true")
    operation.add_argument("--write", action="store_true")
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--tools-output", required=True, type=Path)
    parser.add_argument("--candidate-output", required=True, type=Path)
    args = parser.parse_args()
    tools, candidate = render(args.source.read_bytes())
    outputs = ((args.tools_output, tools), (args.candidate_output, candidate))
    if args.check:
        stale = [str(path) for path, expected in outputs if not path.is_file() or path.read_text(encoding="utf-8") != expected]
        if stale:
            print("generated U5 manifests are stale: " + ", ".join(stale), file=os.sys.stderr)
            return 1
        return 0
    for path, content in outputs:
        _write(path, content)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError) as error:
        print(f"ERROR: {error}", file=os.sys.stderr)
        raise SystemExit(2)
